"""Ready-to-run pyFEMM driver for the EM analysis (RUN ON WINDOWS: FEMM 4.2 +
`pip install pyfemm`). Reads the hand-off package generated by
`python -m motor_nx.cli fea -o fea/` (femm_labels.csv, winding.csv, cross_section.dxf
+ fea_spec.json) and sets up + solves the magnetostatic problem, then reports
torque and per-phase flux linkage. A rotor-rotation loop skeleton for cogging /
back-EMF is included (assign the rotor core + magnets to group 1 first).

This script could not be executed in the Linux build sandbox (FEMM is Windows-only);
it is delivered ready to run. Verify the OD boundary + air-gap sliding band in FEMM."""
import csv, json, os, femm

HERE = os.path.dirname(os.path.abspath(__file__))
spec = json.load(open(os.path.join(HERE, "fea_spec.json")))
Lstk = spec["geometry_mm"]["stack_length"]
Ipk  = spec["excitation"]["peak_current_A_rms"]            # drive at peak for torque
ROTOR_GROUP = 1

femm.openfemm()
femm.newdocument(0)                                        # 0 = magnetics
femm.mi_probdef(0, "millimeters", "planar", 1e-8, Lstk, 30)
femm.mi_readdxf(os.path.join(HERE, "cross_section.dxf"))   # import the cross-section
femm.mi_zoomnatural()

# --- materials (FEMM library; replace Steel BH with the vendor M250-27 curve) -
for m in ("Air", "Copper", "M-19 Steel"):
    femm.mi_getmaterial(m)
femm.mi_getmaterial("NdFeB 40 MGOe")                        # ~N42-class; tune Hc/Br to N42SH
# 3-phase circuits (series); peak phase current, sign handled per block turns
for ph in ("A", "B", "C"):
    femm.mi_addcircprop(ph, 0.0, 1)                         # set currents below
femm.mi_modifycircprop("A", 1,  Ipk*1.41421)
femm.mi_modifycircprop("B", 1, -Ipk*0.70711)
femm.mi_modifycircprop("C", 1, -Ipk*0.70711)

# --- block labels from the recipe ------------------------------------------- #
mat_map = {"Steel": "M-19 Steel", "Air": "Air", "Copper": "Copper", "NdFeB": "NdFeB 40 MGOe"}
with open(os.path.join(HERE, "femm_labels.csv")) as fh:
    for row in csv.DictReader(fh):
        x, y = float(row["x_mm"]), float(row["y_mm"])
        mat = mat_map.get(row["material"], row["material"])
        circ = row.get("circuit") or "<None>"
        turns = int(row["turns"]) if row.get("turns") else 0
        magdir = float(row["magdir_deg"]) if row.get("magdir_deg") else 0.0
        grp = ROTOR_GROUP if row["material"] in ("NdFeB",) or "rotor" in row["note"] else 0
        femm.mi_addblocklabel(x, y)
        femm.mi_selectlabel(x, y)
        femm.mi_setblockprop(mat, 1, 0, circ, magdir, grp, turns)
        femm.mi_clearselected()

# --- outer boundary A = 0 on the stator OD (set the OD arc to this in FEMM) -- #
femm.mi_addboundprop("A0", 0, 0, 0, 0, 0, 0, 0, 0, 0)
# NOTE: select the stator OD arc and apply 'A0' (mi_selectarcsegment + mi_setarcsegmentprop)

femm.mi_saveas(os.path.join(HERE, "motor_femm.fem"))
femm.mi_analyze()
femm.mi_loadsolution()

# --- one operating point: torque + per-phase flux linkage ------------------- #
femm.mo_groupselectblock(ROTOR_GROUP)
T = femm.mo_blockintegral(22)                              # 22 = weighted stress-tensor torque
print("electromagnetic torque (N.m):", T)
for ph in ("A", "B", "C"):
    name, I, V, fl = ("%s" % ph,) + femm.mo_getcircuitproperties(ph)
    print("phase %s : I=%.1f A  flux-linkage=%.4f Wb" % (ph, I, fl))

# --- cogging / back-EMF sweep (rotate rotor group; uncomment after grouping) -
# import numpy as np
# for k in range(0, 61):
#     femm.mi_selectgroup(ROTOR_GROUP); femm.mi_moverotate(0, 0, 1.0); femm.mi_clearselected()
#     femm.mi_analyze(); femm.mi_loadsolution()
#     femm.mo_groupselectblock(ROTOR_GROUP)
#     print(k, femm.mo_blockintegral(22))                 # torque(theta) -> cogging/ripple
femm.closefemm()
